# Generated by Django 5.0.1 on 2024-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_address_author_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
